Miele W6000 WPS Primavera Plus:
  Baumwolle:
    90°:
      :duration_in_min: 149
      :consumption_in_Wh: 2200
    60°:
      :duration_in_min: 119
      :consumption_in_Wh: 1330
    Eco60°:
      :duration_in_min: 179
      :consumption_in_Wh: 820
    40°:
      :duration_in_min: 149
      :consumption_in_Wh: 730
    Eco40°:
      :duration_in_min: 179
      :consumption_in_Wh: 580
  Pflegeleicht:
    40°:
      :duration_in_min: 110
      :consumption_in_Wh: 560
  Synthetik:
    30°:
      :duration_in_min: 56
      :consumption_in_Wh: 380
  Wolle:
    30°:
      :duration_in_min: 39 
      :consumption_in_Wh: 230
  Imprägnieren:
    40°:
      :duration_in_min: 39 
      :consumption_in_Wh: 350
  Express20:
    40°:
      :duration_in_min: 20 
      :consumption_in_Wh: 320
  AutomaticPlus:
    40°:
      :duration_in_min: 87 
      :consumption_in_Wh: 520
  DunklesJeans:
    40°:
      :duration_in_min: 72 
      :consumption_in_Wh: 600
  Oberhemden:
    60°:
      :duration_in_min: 71 
      :consumption_in_Wh: 950
  IntensivPlus:
    60°:
      :duration_in_min: 167
      :consumption_in_Wh: 1650

Miele T8861 WP Edition 111:
  Baumwolle:
    Schranktrocken:
      Normal:
        :duration_in_min: 105
        :consumption_in_Wh: 1600
      SchonenPlus:
        :duration_in_min: 140
        :consumption_in_Wh: 2150
    Bügelfeucht:
      :duration_in_min: 69
      :consumption_in_Wh: 1100
  Pflegeleicht:
    Schranktrocken:
      Normal:
        :duration_in_min: 47
        :consumption_in_Wh: 600
      SchonenPlus:
        :duration_in_min: 49
        :consumption_in_Wh: 650
    Bügelfeucht:
      :duration_in_min: 41
      :consumption_in_Wh: 500
  AutomaticPlus:
    Schranktrocken:
      :duration_in_min: 99
      :consumption_in_Wh: 1500
  Oberhemden:
    Schranktrocken:
      Normal:
        :duration_in_min: 53
        :consumption_in_Wh: 700
      SchonenPlus:
        :duration_in_min: 59
        :consumption_in_Wh: 750
  Schonglätten:
    :duration_in_min: 30
    :consumption_in_Wh: 350
  Imprägnieren:
    Schranktrocken:
      :duration_in_min: 85
      :consumption_in_Wh: 1250
  Jeans:
    Schranktrocken:
      Normal:
        :duration_in_min: 94
        :consumption_in_Wh: 1400
      SchonenPlus:
        :duration_in_min: 99
        :consumption_in_Wh: 1450
  Express:
    Schranktrocken:
      :duration_in_min: 75
      :consumption_in_Wh: 1100
  Wolle:
    :duration_in_min: 20
    :consumption_in_Wh: 200
  BaumwollenHygiene:
    Schranktrocken:
      :duration_in_min: 126
      :consumption_in_Wh: 1900
